spring:
  profiles:
    active: local
  config:
    import: "optional:file:.env[.properties]"

  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
      defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
        format_sql: false
logging:
  level:
    root: INFO
    io.opentelemetry: DEBUG


management:
  metrics:
    export:
      otlp:
        enabled: true
        endpoint: http://otel-collector:4318
    enable:
      all: true
      jvm: true
  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true

otel:
  resource:
    attributes:
      service.name: ticket-service
  exporter:
    otlp:
      url: http://otel-collector:4317
      protocol: grpc

snail-catch:
  enabled: true
  repository-pointcut: execution(* com.ticketon.ticketon.domain..repository..*(..))
  api-key: 13a4d744b37046e2b62f90077c0936f8

server:
  tomcat:
    threads:
      max: 200
      min-spare: 10
      max-queue-capacity: 2147483647
    max-connections: 8192
    accept-count: 100
    connection-timeout: 60000
    keep-alive-timeout: 30000
    max-http-header-size: 8192
    max-keep-alive-requests: 100

