spring:
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    initialization-mode: create
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLDialect
      defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
        format_sql: false

  redis:
    host: localhost
    port: 6379
    timeout: 60000ms

  logging:
    level:
      root: INFO
      io.opentelemetry: DEBUG

management:
  metrics:
    export:
      otlp:
        enabled: true
        endpoint: http://localhost:4317 # OTEL Collector의 gRPC 포트
    enable:
      all: true
      jvm: true
  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true


otel:
  resource:
    attributes:
      service.name: ticketon-service
  exporter:
    otlp:
      endpoint: http://localhost:4317
      protocol: grpc