spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_DOCKER_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      initialization-fail-timeout: 1
      read-only: false
      leak-detection-threshold: 0


kafka:
  bootstrap-servers: kafka:9092
  consumer:
    group-id: test-group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer


redis:
  queue:
    host: redis
    port: 6379

  cache:
    host: redis
    port: 6380