global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]
  - job_name: 'redis-exporter'
    static_configs:
      - targets: [ 'redis-exporter:9121' ]
  - job_name: 'ticket-service'
    static_configs:
      - targets: ['otel-collector:8889']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'k6'
    static_configs:
      - targets: [ 'host.docker.internal:6565' ]