auth_enabled: false

server:
  log_level: warn
  http_listen_port: 3200
  grpc_listen_port: 4318

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:55681

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  trace_idle_period: 10s
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 140h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo
    wal:
      path: /tmp/tempo/wal

querier: {}

query_frontend: {}

memberlist:
  join_members: ["127.0.0.1"]

overrides:
  metrics_generator_processors: []
