version: '3.7'

services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.93.0
    container_name: otel-collector
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otel/otel-collector-config.yaml
    command: --config=/etc/otel/otel-collector-config.yaml
    networks:
      - monitoring


  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
    networks:
      - monitoring
    volumes:
      - grafana-storage:/var/lib/grafana

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    command: -config.file=/etc/promtail/config.yml
    ports:
      - "9080:9080"
    volumes:
      - ./loki/promtail-config.yml:/etc/promtail/config.yml
      - /Users/sinminseok12/Desktop/Ticket-on/ticketon/logs:/var/log
    depends_on:
      - loki
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge


volumes:
  grafana-storage:
