apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-script-config
data:
  queue-enter-test.js: |
    import http from 'k6/http';
    import { check } from 'k6';
    import { uuidv4 } from 'https://jslib.k6.io/k6-utils/1.2.0/index.js';

    export const options = {
      scenarios: {
        steady_load: {
          executor: 'constant-arrival-rate',
          rate: 5000,
          timeUnit: '1s',
          duration: '3s',
          preAllocatedVUs: 3000,
          maxVUs: 4000,
        },
      },
    };

    export default function () {
      const uniqueId = uuidv4();
      const email = `user-${uniqueId}@example.com`;

      const headers = {
        'Content-Type': 'application/json',
      };

      const body = JSON.stringify({ email });

      const res = http.post('http://43.201.231.114:8082/v1/api/queues/enter', body, { headers });

      check(res, {
        'status is 200': (r) => r.status === 200,
        'contains 요청 수신 완료': (r) => r.body.includes('요청 수신 완료'),
      });
    }
