name: Build, Push and Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Upload nginx.conf to EC2
          uses: appleboy/scp-action@v0.1.4
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            source: ./nginx/nginx.conf
            target: /home/ubuntu/ticket-app/nginx/

      - name: Upload k6 test script
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_K6_PUBLIC_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_K6_SSH_KEY }}
          source: ./stress-test/k6-scripts/queue-enter-test.js
          target: /home/ubuntu/k6-tests/

      # ✅ Build ticket-api-server
      - name: Build ticket-api-server jar
        run: ./gradlew :ticket-api-server:bootJar

      - name: Build ticket-api-server Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ticket-api-server:latest ./ticket-api-server

      # ✅ Build ticket-queue-server
      - name: Build ticket-queue-server jar
        run: ./gradlew :ticket-queue-server:bootJar

      - name: Build ticket-queue-server Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ticket-queue-server:latest ./ticket-queue-server

      # ✅ Docker Login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ✅ Push both images
      - name: Push ticket-api-server image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ticket-api-server:latest

      - name: Push ticket-queue-server image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ticket-queue-server:latest

      # ✅ Upload .env
      - name: Create .env file from secrets
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_DOCKER_URL=${{ secrets.DB_DOCKER_URL }}" >> .env
          echo "DB_LOCAL_URL=${{ secrets.DB_LOCAL_URL }}" >> .env
          echo "DB_USER_NAME=${{ secrets.DB_USER_NAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "LOKI_URL=${{ secrets.LOKI_URL }}" >> .env
          echo "OTEL_EXPORTER_OTLP_ENDPOINT=${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}" >> .env
          echo "TOSS_SECRET_KEY=${{ secrets.TOSS_SECRET_KEY }}" >> .env
          echo "TOSS_CLIENT_KEY=${{ secrets.TOSS_CLIENT_KEY }}" >> .env

      - name: Upload .env to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ./.env
          target: /home/ubuntu/ticket-app/

      # ✅ Upload monitoring-config
      - name: Clean old monitoring-config on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf /home/ubuntu/ticket-app/monitoring-config

      - name: Upload monitoring config to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ./monitoring-config
          target: /home/ubuntu/ticket-app/

      # ✅ Upload docker-compose.yml
      - name: Upload docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ./docker-compose.yml
          target: /home/ubuntu/ticket-app/

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/ticket-app
            docker-compose down
            docker-compose pull
            docker-compose up -d
